volumes:
  ace_postgresql_data: {}

networks:
  ace:
    name: ace
    driver: bridge
    external: true

services:
  ace-keycloak:
    container_name: ace-keycloak
    build:
      context: .
      dockerfile: Dockerfile_KC
      no_cache: true
    depends_on:
      - ace-postgresql
    networks:
      - ace
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:9000/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 15
    environment:
      # This configuration assumes a reverse proxy that handles SSL
      KC_HTTP_ENABLED: true
      KC_HTTP_PORT: 8081
      KC_PROXY: edge
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_RELATIVE_PATH: # CHANGE ME if necessary, e.g. /keycloak
      KC_HOSTNAME: # CHANGE ME, e.g. https://ace.server.com
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_LOG_LEVEL: DEBUG
      TZ: Europe/Berlin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://ace-postgresql:5432/keycloak?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Berlin
      KC_DB_USERNAME: # CHANGE ME, e.g. ace-manager
      KC_DB_PASSWORD: # CHANGE ME, e.g. ace-manager-password
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: # CHANGE ME, e.g. keycloak-admin # username of the keycloak admin account
      KEYCLOAK_ADMIN_PASSWORD: # CHANGE ME, e.g. keycloak-admin-password # password of the keycloak admin account
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_FEATURES: docker,token-exchange,preview
    command: start
    ports:
      - "8081:8081" # remapping of keycloak to port 8081, since ACE will be running on 8080
      - "8443:8443"
      - "9000:9000" # enables healthcheck
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  ace-postgresql:
    container_name: ace-postgresql
    image: postgres:15.3-alpine
    networks:
      - ace
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ace-manager -d ace"]
      interval: 10s
      timeout: 5s
      retries: 15
    ports:
      - "5432:5432"
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_USER= # CHANGE ME, e.g. ace-manager # username of the postgres DB user, e.g. ace-manager
      - POSTGRES_PASSWORD= # CHANGE ME, e.g. ace-manager-password # password of the postgres DB user
      - POSTGRES_DB=ace
    volumes:
      - ./src/main/resources/db/ace-schema.sql:/docker-entrypoint-initdb.d/ace-schema.sql
      - ./src/main/resources/db/keycloak-example.sql:/docker-entrypoint-initdb.d/keycloak-example.sql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ace_postgresql_data:/var/lib/postgresql/data
