server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  servlet:
    encoding:
      charset: UTF-8
      force: true
  max-http-request-header-size: 6KB

logging:
  level:
    org.trustdeck: ${TRUSTDECK_LOG_LEVEL:INFO}
    root: ERROR

spring:
  #application:
  #  name: TRUSTDECK
  jpa:
    open-in-view: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  main:
    allow-circular-references: true
  servlet:
    multipart:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          # Custom section starts
          # Server-uri without /auth since keycloak 17
          principal-attribute: preferred_username
          server-uri: ${KEYCLOAK_SERVER_URI}
          realm: ${KEYCLOAK_REALM_NAME}
          truststore: ${TRUSTSTORE_PATH}
          truststore-password: ${TRUSTSTORE_PASSWORD}
          client-id: ${KEYCLOAK_CLIENT_ID}
          client-secret: ${KEYCLOAK_CLIENT_SECRET}
          # Custom section ends
          jws-algorithm: RSA256
          issuer-uri: ${KEYCLOAK_HOSTNAME}/realms/${spring.security.oauth2.resourceserver.jwt.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

audittrail:
  oidc-group-mapper:
    token-claim-name: trustdeck_groups
    group-names:
      isHuman: Human
      isTechnical: Technical
      isNoAuditing: Unaudited
      isAuditEverything: AuditEverything
  cleanup:
    enabled: true
    # Cron expression for cleanup task. Default: Every day at 2:00 AM.
    cron: "0 0 2 * * ?"
    # Retention period in days for audit entries.
    retention-days: 3650

app:
  response:
    # Possible entries are application/json or text/plain
    preferred-accept-mime-type: application/json
  datasource:
    trustdeck:
      url: jdbc:postgresql://${DATABASE_TRUSTDECK_HOST:localhost}:${DATABASE_TRUSTDECK_PORT:5432}/trustdeck
      username: ${DATABASE_TRUSTDECK_USER}
      password: ${DATABASE_TRUSTDECK_PASSWORD}
      configuration:
        maximum-pool-size: 20
  roles:
    # Name of all possible rights -- used for rights and roles management
    ACE:
      - domain:delete
      - domain:read
      - domain:read-salt
      - domain:read-subtree
      - domain:update
      - domain:update-complete
      - domain:update-salt
      - pseudonym:create
      - pseudonym:create-batch
      - pseudonym:delete
      - pseudonym:delete-batch
      - pseudonym:read
      - pseudonym:read-batch
      - pseudonym:update
      - pseudonym:update-complete
      - pseudonym:update-batch
      - pseudonym:link
      - complete-view
    KING:
      - project:read
      - project:update
      - project:delete
      - image:create
      - image:read
      - image:update
      - image:delete
      - type:create
      - type:read
      - type:update
      - type:delete
      - type:search
      - instance:create
      - instance:read
      - instance:update
      - instance:delete
      - instance:search
      - instance:record-linkage
      - instance:list-pseudonyms
    global:
      - domain:create
      - domain:create-complete
      - domain:list-all
      - project:create
      - project:list-all
      - base-type:create
      - base-type:read
      - roles:delete
      - table:delete
      - table:read-storage
