volumes:
  ace_postgresql_data: {}

networks:
  ace:
    name: ace
    driver: bridge
    external: true

services:
  ace-keycloak:
    container_name: ace-keycloak
    build:
      context: .
      dockerfile: Dockerfile_Keycloak
      args:
        CHAIN_PEM_FILE_PATH: ${CHAIN_PEM_PATH}
        RSA_CRT_FILE_PATH: ${RSA_CRT_PATH}
        ECC_CRT_FILE_PATH: ${ECC_CRT_PATH}
        ORGANIZATION_CA_PEM_FILE_PATH: ${ORGANIZATION_CA_PEM_PATH}
      no_cache: true
    image: keycloak-with-curl-and-certs:latest
    depends_on:
      - ace-postgresql
    networks:
      - ace
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:9000/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 15
    environment:
      # This configuration assumes a reverse proxy that handles SSL
      KC_HTTP_ENABLED: true
      KC_HTTP_PORT: 8081
      KC_PROXY: edge
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_RELATIVE_PATH: ${KEYCLOAK_RELATIVE_PATH}
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME}
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_LOG_LEVEL: ${KEYCLOAK_LOG_LEVEL:-INFO}
      TZ: Europe/Berlin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://ace-postgresql:5432/keycloak?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Berlin
      KC_DB_USERNAME: ${DATABASE_KEYCLOAK_USER}
      KC_DB_PASSWORD: ${DATABASE_KEYCLOAK_PASSWORD}
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_FEATURES: docker,token-exchange,preview
    command: start
    ports:
      - "8081:8081" # remapping of keycloak to port 8081, since ACE will be running on 8080
      - "8443:8443"
      - "9000:9000" # enables healthcheck
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  ace-postgresql:
    container_name: ace-postgresql
    image: postgres:latest
    networks:
      - ace
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_ACE_USER} -d ace"]
      interval: 10s
      timeout: 5s
      retries: 15
    ports:
      - "5432:5432"
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_USER=${DATABASE_ACE_USER}
      - POSTGRES_PASSWORD=${DATABASE_ACE_PASSWORD}
      - POSTGRES_DB=ace
    volumes:
      - ../src/main/resources/db/ace-example.sql:/docker-entrypoint-initdb.d/ace-example.sql
      - ../src/main/resources/db/keycloak-example.sql:/docker-entrypoint-initdb.d/keycloak-example.sql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ace_postgresql_data:/var/lib/postgresql/data
