volumes:
  trustdeck_postgresql_data: {}

networks:
  trustdeck:
    name: trustdeck
    driver: bridge

services:
  trustdeck-postgresql:
    image: postgres:latest
    container_name: trustdeck-postgresql
    networks:
      - trustdeck
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_TRUSTDECK_USER} -d trustdeck"]
      interval: 10s
      timeout: 5s
      retries: 15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_TRUSTDECK_USER}
      POSTGRES_PASSWORD: ${DATABASE_TRUSTDECK_PASSWORD}
      POSTGRES_DB: trustdeck
      TZ: Europe/Berlin
    volumes:
      - ../src/main/resources/db/trustdeck-example.sql:/docker-entrypoint-initdb.d/trustdeck-example.sql
      - ../src/main/resources/db/keycloak-example.sql:/docker-entrypoint-initdb.d/keycloak-example.sql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - trustdeck_postgresql_data:/var/lib/postgresql

  trustdeck-keycloak:
    container_name: trustdeck-keycloak
    build:
      context: ..
      dockerfile: docker/Dockerfile_Keycloak_dev
      no_cache: true
    image: keycloak-dev:latest
    depends_on:
      - trustdeck-postgresql
    networks:
      - trustdeck
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8080/health/ready"]
      interval: 5s
      timeout: 2s
      retries: 15
    environment:
      KC_HTTP_ENABLED: false
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_LOG_LEVEL: ${KEYCLOAK_LOG_LEVEL:-INFO}
      TZ: Europe/Berlin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://trustdeck-postgresql:5432/keycloak?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Berlin
      KC_DB_USERNAME: ${DATABASE_KEYCLOAK_USER}
      KC_DB_PASSWORD: ${DATABASE_KEYCLOAK_PASSWORD}
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_FEATURES: docker,token-exchange,preview
    # Do not use this in production see this: https://www.keycloak.org/server/containers
    command: start-dev
    ports:
      - "8081:8080"
      - "8443:8443"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
