# Add curl to keycloak to enable health checks
# Use an image that includes a package manager
FROM registry.access.redhat.com/ubi9 AS ubi-micro-build

# Switch to root user
USER root

# Create folder and install curl in it
RUN mkdir -p /mnt/rootfs
RUN dnf install --installroot /mnt/rootfs curl --releasever 9 --setopt install_weak_deps=false --nodocs -y && \
    dnf --installroot /mnt/rootfs clean all && \
    rpm --root /mnt/rootfs -e --nodeps setup

# Start creating standard keycloak and copy the curl installation into the standard image
FROM quay.io/keycloak/keycloak:latest
COPY --from=ubi-micro-build /mnt/rootfs /